### PR TITLE
Fix node status update

### LINKED ISSUE #164: Fix the status update for the Crusher node on the manager server
When Crusher is installed on a node, the manager server should display a green light in the UI to show the Crusher node is functioning correctly. Currently, it shows the gray light instead.

- Issue Details
When operating Crusher with local configuration, it continuously attempts to reconnect with the manager.
The Crusher log indicates that the connection is established every minute.
Presumably, when a ping is sent, it receives `RequestCode::EchoRequest` and goes back into the `connect()` loop.

It's reproducible as follows:

- Node Configuration
node1: manager, ti-container
node2: The remainder (including Crusher)
node3: sensor

- UI Status
All nodes are registered and have been applied.

Logs:

...
2025-03-04T10:28:55.936879Z  INFO Connection established to the Manager server masked:38390
2025-03-04T10:28:58.179399Z  INFO Connection established to the Manager server masked:38390
2025-03-04T10:29:15.352126Z  INFO Connection established to the Manager server masked:38390
2025-03-04T10:29:16.343895Z  INFO Connection established to the Manager server masked:38390
2025-03-04T10:30:30.847888Z  INFO Connection established to the Manager server masked:38390
2025-03-04T10:31:30.846951Z  INFO Connection established to the Manager server masked:38390
2025-03-04T10:32:30.849835Z  INFO Connection established to the Manager server masked:38390
...

### PR DESCRIPTION
**Pull request by danbi2990**
Closes #164

### CODE REVIEW

File: src/request.rs [hunk 1]
```diff
@@ -79,7 +81,11 @@ impl Client {
                         review_protocol::request::handle(self, &mut send, &mut recv).await?;
                     }
                     Err(e) => {
+                        // This occurs when the manager goes offline (ApplicationClose).
```
Comment (sehkone) [inline src/request.rs:84]: Is 'ApplicationClose' a term or an enum variant? I just found a similar variant `ConnectionError::ApplicationClosed`, but can't find it.

Comment (danbi2990) [reply src/request.rs]: My mistake—it’s an enum variant, and I've updated it.

File: src/request.rs [hunk 2]
```diff
@@ -79,7 +81,11 @@ impl Client {
                         review_protocol::request::handle(self, &mut send, &mut recv).await?;
                     }
                     Err(e) => {
+                        // This occurs when the manager goes offline (`ApplicationClosed`).
+                        // Crusher might have to wait until it's online.
```
Comment (sophie-cluml) [inline src/request.rs:85]: I think this comment might be mislead people to think that this Err block is hit only when `ApplicationClosed` happens. This Err block is hit when connection error occurs, which includes `ApplicationClosed` error. So I think it might be rather beneficial not to have the code comment. (I also think it is quite natural to think that Crusher needs to retry connecting to the manager module, if the connection itself fails to get established in the first place.)

Comment (danbi2990) [reply src/request.rs]: Removed the comment.

File: CHANGELOG.md [hunk 3]
```diff
@@ -5,6 +5,16 @@ file is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/), and
...
 
+## [Unreleased]
+
+### Fixed
+
+- Fixed the issue where the node status was not updated in the manager server
+  because Crusher disconnected after handling a single request. The manager
+  server sends two consecutive requests (resource and ping) to check the node
+  status. If Crusher disconnects after processing the first request, the
+  subsequent request (ping, in this case) is not handled properly.
```
Comment (sophie-cluml) [inline CHANGELOG.md:16]: Upon the PR, I came to think that the node status not updating was one of the symptoms, and the underlying issue seems to be that the connection closes immediately after handling a single request. I think `resource` and `ping` are just examples, so what do you think about framing the changelog explanation around the resolution of the underlying root cause itself?

Comment (danbi2990) [reply CHANGELOG.md]: Updated the changelog.

**Review by sophie-cluml — APPROVED** [review]
