### PR TITLE
Fix connection behavior after manager restart

### LINKED ISSUE #190: Crusher fails to reconnect when the manager is restarted
After the manager is restarted, Crusher shows the following message and does not attempt to reconnect:

> Failed to accept bidirectional stream: ApplicationClosed(ApplicationClose { error_code: 0, reason: b"" })

### PR DESCRIPTION
**Pull request by danbi2990**
Update the `connect` method to properly check whether the existing connection has been closed before attempting to reuse it.

Closes #190

### CODE REVIEW

File: src/request.rs [hunk 1]
```diff
@@ -112,29 +112,33 @@ impl Client {
     }
 
     async fn connect(&mut self) -> Result<&Connection> {
-        if let Some(ref conn) = self.connection {
-            return Ok(conn);
+        let needs_reconnect = match self.connection.as_ref() {
+            Some(conn) => conn.close_reason().is_some(),
+            None => true,
+        };
```
Comment (sehkone) [inline src/request.rs:118]: I think this can be refactored using method chaining. I believe that would make the code simpler and more idiomatic in Rust.

Comment (danbi2990) [reply src/request.rs]: Applied the suggested adjustment.

**Comment by kimhanbeom** [comment]
I've tested with the current branch and it doesn't reconnect when I restart the data_store. Could you please also check this part?

**Comment by danbi2990** [comment]
> I've tested with the current branch and it doesn't reconnect when I restart the data_store. Could you please also check this part?

The bug has been fixed. Could you confirm whether the following reproduction steps are correct?

Bug reproduction steps:

1. Run the manager, data-store and Crusher
2. Insert a sampling policy into the manager
3. Restart the data-store

**Comment by kimhanbeom** [comment]
if we disconnect while only maintaining a connection (i.e., no policy insert), it will not reconnect.

Bug reproduction steps:
- Run the manager, data-store and Crusher
- Restart the data-store

**Comment by danbi2990** [comment]
> Bug reproduction steps:
> 
> * Run the manager, data-store and Crusher
> * Restart the data-store

The issue has been fixed.

While addressing it, I discovered the `Connection::closed()` method, which can be used to detect connection termination. This could potentially eliminate the need to pass around `connection_notify`.
If you're okay with it, I'll open a new issue to track this refactoring.

**Review by kimhanbeom — APPROVED** [review]
LGTM
